### ISSUE TITLE
The README.md contains a dead link to the archtecture

### ISSUE THREAD

**Issue by paulmillar** [panosc-eu/panosc-federated-search-service#2]
**Describe the bug**

The README.md file contains a link (the word "Architecture" in the sentence "Architecture of search API system") under the heading "Documentation".  This link points to a confluence page `https://confluence.panosc.eu/display/wp3/Search+aggregation`.  However, my browser cannot access this page.  An attempt to follow the link results in the browser hanging for a while before declaring the link dead.

**To Reproduce**

1. Navigate browser to the page https://github.com/panosc-eu/panosc-federated-search-service
2. Select the `Architecture` link, under the `Documentation` header from the rendered page.
3. Wait for the browser to time out the request.

**Expected behaviour**

I would expect to see a valid web page.

**Desktop (please complete the following information):**
- OS (Debian Linux
- Browser: Firefox

**Additional context**

I have verified that my laptop cannot create a TCP connection to the target host (`confluence.panosc.eu`) and port (`443`).
The connection is attempted (sending SYN packages), however no SYN+ACK, ICMP or RST packet is returned.
This is symptomatic of a firewall.

**Comment by nitrosx** [comment]
@paulmillar : thank you for reporting the issue. I will take care in the next documentation update

**Comment by nitrosx** [comment]
Removed documentation section with dead link. 
Once the documentation comes back online, I will add the section once more
